export const APP_FONTS = {
  FONT_REGULAR: 'SalesforceSans-Regular',
  FONT_BOLD: 'SalesforceSans-Bold',
  FONT_LIGHT: 'SalesforceSans-Light'
};

export const APP_THEME = {
  APP_BASE_COLOR: '#01579b',
  NAVIGATION_BACKGROUND: '#f8f8f8',
  APP_BASE_FONT_COLOR: '#01579b',
  APP_DARK_FONT_COLOR: '#2b2826',
  APP_LIGHT_FONT_COLOR: '#706e6b',
  APP_BORDER_COLOR: '#dedcdb',
  APP_ERROR_COLOR: '#94221c',
  APP_LIST_HEADER_COLOR: '#e1f5fe',
  APP_WHITE: 'white'
};

export const APP_ROUTE = {
  LOGIN: 'Login'
};

export const ASYNC_STORAGE_KEYS = {
  SALESFORCE_ACCESS_TOKEN: '@SalesforceAccessToken',
  SALESFORCE_INSTANCE_URL: '@SALESFORCE_INSTANCE_URL',
  CDW_WORKED_ID: '@CDW_WORKED_ID',
  CDW_WORKED_NAME: '@CDW_WORKED_NAME',
  AREA_CODE: '@AREA_CODE',
  NETWORK_CONNECTIVITY: '@NETWORK_CONNECTIVITY',
  LANGUAGE: '@LANGUAGE'
};
