name: unit test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: 'Checkout source code'
        uses: actions/checkout@v2

      # Install npm dependencies
      - name: 'Install npm dependencies'
        run: npm install

      # Eslint
      - name: 'Validate'
        run: npm run validate

      # Create mock .env
      - name: 'Create mock env file'
        run: echo "LOGIN_API_URL=https://test.herokuapp.com/login\nREFRESH_KEY=12345" > .env

      # Unit Test
      - name: 'Unit test'
        run: npm run test

      # Delete mock .env
      - name: 'Delete mock env file'
        run: rm -f .env

      # Upload code coverage data
      - name: 'Upload code coverage to Codecov.io'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}